### ISSUE TITLE
element id value is AD.usablePeriod instead of AD.useablePeriod[x]

### ISSUE THREAD

**Issue by oliveregger** [HL7/cda-core-2.0#12]
The Address CDA Type AD has a usablePeriod element. The useablePeriod can have multiple types, therefore the element ID should have an [x] in the element id value like in the path value.

    <element id="AD.useablePeriod[x]">
      <extension url="http://hl7.org/fhir/StructureDefinition/elementdefinition-defaulttype">
        <valueString value="SXPR_TS"/>
      </extension>
      <path value="AD.useablePeriod[x]"/>

With the current definition igpublisher hangs, see https://github.com/HL7/fhir-ig-publisher/issues/36.

**Comment by seanmcilvenna** [comment]
The PR suggested by @oliveregger seems to have fixed the problem. The build is now succeeding. Closing this out.
