### ISSUE TITLE
Fixes a few issues with the template

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/cda-core-2.0#14]
- The title of the pages. Currently is "Australian Based Implementation Guide". Would like it to be "Clinical Document Architecture (CDA) 2.0".
- Would like to change the navbar to have "Models" and "Data Types" separately.
- Would like some custom pages to include narrative guidance from the CDA spec.

**Comment by oliveregger** [comment]
As HL7 is defining a new new ig template structure it would make maybe sense to switch later to that?

**Comment by seanmcilvenna** [comment]
I agree. That would make sense. Either way, though, work has to be done to either fix the existing template or create the new one. This ticket is a placeholder for that work.
