### ISSUE TITLE
id elements in V3 Acts and II datatype extension attribute conflict with base Element

### ISSUE THREAD

**Issue by oliveregger** [HL7/CDA-core-2.0#21]
Some V3 Acts have an id element inside, e.g:

- ClinicalDocument.id [1..1]
- SubstanceAdministration.id [0..*]

This V3 Acts are represented as Logical Models in FHIR. [Logical Models have a base of "Element" or another logical model.](http://hl7.org/fhir/structuredefinition-definitions.html) The base content of the FHIR [Element](http://hl7.org/fhir/element.html#Element) has already an id and an extension element, which have different datatypes (string) and defined cardinality.

This leads to the following problems:
- SubstanceAdministration.id: illegal constrained type http://hl7.org/fhir/cda/StructureDefinition/II from string in http://hl7.org/fhir/StructureDefinition/Element
- Element SubstanceAdministration.id: derived max (*) cannot be greater than base max (1)

A related problem occurs with the II datatype which has an extension attribute which conflicts with the extensions defined in Element.

**Comment by grahamegrieve** [comment]
I think that this is first of all a methodology problem in FHIR itself. Can you make a task for MnM to talk about this please

**Comment by oliveregger** [comment]
[#25031](https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=25031) Summary: CDA: id elements in V3 Acts and II datatype extension attribute conflict with FHIR base Element

**Comment by oliveregger** [comment]
this is solved with R5 and using Base, thanks!
